package com.arthum.admin.utility;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

import javax.annotation.PostConstruct;

import org.springframework.stereotype.Component;

@Component
public class DropDownUtility {

	public String getState(int stateId) {
		HashMap<Integer, String> hmap = new HashMap<Integer, String>();
		hmap.put(1,"Andhra Pradesh");
		hmap.put(2,"Arunachal Pradesh");
		hmap.put(3,"Assam");
		hmap.put(4,"Bihar");
		hmap.put(5,"Chhattisgarh");
		hmap.put(27,"Dadar/Nagar Haveli");
		hmap.put(28,"Delhi");
		hmap.put(6,"Goa");
		hmap.put(7,"Gujarat");
		hmap.put(8,"Haryana");
		hmap.put(9,"Himachal Pradesh");
		hmap.put(10,"Jharkhand");
		hmap.put(11,"Karnataka");
		hmap.put(12,"Madhya Pradesh");
		hmap.put(13,"Maharashtra");
		hmap.put(14,"Manipur");
		hmap.put(15,"Meghalaya");
		hmap.put(16,"Mizoram");
		hmap.put(17,"Nagaland");
		hmap.put(18,"Odisha");
		hmap.put(29,"Puducherry");
		hmap.put(19,"Punjab");
		hmap.put(20,"Rajasthan");
		hmap.put(21,"Tamil Nadu");
		hmap.put(22,"Telangana");
		hmap.put(23,"Tripura");
		hmap.put(24,"Uttar Pradesh");
		hmap.put(25,"Uttarakhand");
		hmap.put(26,"West Bengal");
		
		String state = hmap.get(stateId);
		
		return state;
	}
	
	public String getArthmateDocCode(String documentName) {
		HashMap<String,String> hmap = new HashMap<String,String>();
		
		/*hmap.put("001","agreement");
		hmap.put("002","loan_sanction_letter");
		hmap.put("003","selfie");
		hmap.put("004","address_proof");
		hmap.put("005","pan_card");
		hmap.put("006","aadhar_card");
		hmap.put("007","cheques");
		hmap.put("008","nach_form");
		hmap.put("009","other");
		hmap.put("010","msp_receipt");
		hmap.put("011","app_perm_addr_prf");
		hmap.put("012","app_ebill");
		hmap.put("013","app_photo_id_prf");
		hmap.put("014","app_rent_agrmnt");
		hmap.put("015","app_gas_bill");
		hmap.put("016","app_other");
		hmap.put("017","co_app_addr_prf");
		hmap.put("018","co_app_perm_addr_prf");
		hmap.put("019","co_app_pan_card");
		hmap.put("020","co_app_aadhar_card");
		hmap.put("021","co_app_ebill");
		hmap.put("022","co_app_photo_id_prf");
		hmap.put("023","co_app_rent_agrmnt");
		hmap.put("024","co_app_gas_bill");
		hmap.put("025","co_app_other");
		hmap.put("026","guar_addr_prf");
		hmap.put("027","guar_perm_addr_prf");
		hmap.put("028","guar_pan_card");
		hmap.put("029","guar_aadhar_card");
		hmap.put("030","guar_ebill");
		hmap.put("031","guar_photo_id_prf");
		hmap.put("032","guar_rent_agrmnt");
		hmap.put("033","guar_gas_bill");
		hmap.put("034","guar_other");
		hmap.put("035","buss_addr_prf");
		hmap.put("036","buss_perm_addr_prf");
		hmap.put("037","buss_pan_card");
		hmap.put("038","buss_ebill");
		hmap.put("039","buss_rent_agrmnt");
		hmap.put("040","buss_shop_act");
		hmap.put("041","buss_gst_certifi");
		hmap.put("042","buss_itr_1");
		hmap.put("043","buss_itr_2");
		hmap.put("044","buss_audit_reprt");
		hmap.put("045","buss_bank_stmnts");
		hmap.put("046","buss_other");
		hmap.put("047","cibil_brwr");
		hmap.put("048","cibil_co_brwr");
		hmap.put("049","repayment_track");
		hmap.put("050","fl_reprt");
		hmap.put("051","insurance_frm");
		hmap.put("052","insurance_calculator_page");
		hmap.put("053","dpn");
		hmap.put("054","id_proof");
		hmap.put("055","app_perm_addr_prf");
		hmap.put("056","app_ebill");
		hmap.put("057","app_photo_id_prf");
		hmap.put("058","app_rent_agree");
		hmap.put("059","app_gas_bill");
		hmap.put("060","app_other");
		hmap.put("061","borro_itr_1");
		hmap.put("062","borro_itr_2");
		hmap.put("063","borro_bank_stmt");
		hmap.put("064","borro_other");
		hmap.put("065","borro_sal_slip");
		hmap.put("066","employee_id_card");
		hmap.put("067","cibil_borro");
		hmap.put("068","repay_track");
		hmap.put("069","fi_report");
		hmap.put("070","ins_form");
		hmap.put("071","ins_cal_page");
		hmap.put("072","co_app_addr_prf");
		hmap.put("073","co_app_perm_addr_prf");
		hmap.put("074","co_app_pan_card");
		hmap.put("075","co_app_aadhar_card");
		hmap.put("076","co_app_ebill");
		hmap.put("077","co_app_photo_id_prf");
		hmap.put("078","co_app_rent_agree");
		hmap.put("079","co_app_gas_bill");
		hmap.put("080","co_app_other");
		hmap.put("081","cibil_co_borro");
		hmap.put("082","co_app_bank stmt");
		hmap.put("083","other_1");
		hmap.put("084","other_2");
		hmap.put("085","other_3");
		hmap.put("086","business_addr_prf");
		hmap.put("087","business_perm_addr_prf");
		hmap.put("088","business_pan_card");
		hmap.put("089","business_ebill");
		hmap.put("090","business_rent_agree");
		hmap.put("091","business_shop_act");
		hmap.put("092","business_gst_certifi");
		hmap.put("093","business_itr_1");
		hmap.put("094","business_itr_2");
		hmap.put("095","business_audit_report");
		hmap.put("096","business_bank_stmt");
		hmap.put("097","business_other");
		hmap.put("098","cibil");
		hmap.put("099","bank_stmnts");*/

		hmap.put("agreement","001");
		hmap.put("loan_sanction_letter","002");
		hmap.put("selfie","003");
		hmap.put("address_proof","004");
		hmap.put("pan_card","005");
		hmap.put("aadhar_card","006");
		hmap.put("cheques","007");
		hmap.put("nach_form","008");
		hmap.put("other","009");
		hmap.put("msp_receipt","010");
		hmap.put("app_perm_addr_prf","011");
		hmap.put("app_ebill","012");
		hmap.put("app_photo_id_prf","013");
		hmap.put("app_rent_agrmnt","014");
		hmap.put("app_gas_bill","015");
		hmap.put("app_other","016");
		hmap.put("co_app_addr_prf","017");
		hmap.put("co_app_perm_addr_prf","018");
		hmap.put("co_app_pan_card","019");
		hmap.put("co_app_aadhar_card","020");
		hmap.put("co_app_ebill","021");
		hmap.put("co_app_photo_id_prf","022");
		hmap.put("co_app_rent_agrmnt","023");
		hmap.put("co_app_gas_bill","024");
		hmap.put("co_app_other","025");
		hmap.put("guar_addr_prf","026");
		hmap.put("guar_perm_addr_prf","027");
		hmap.put("guar_pan_card","028");
		hmap.put("guar_aadhar_card","029");
		hmap.put("guar_ebill","030");
		hmap.put("guar_photo_id_prf","031");
		hmap.put("guar_rent_agrmnt","032");
		hmap.put("guar_gas_bill","033");
		hmap.put("guar_other","034");
		hmap.put("buss_addr_prf","035");
		hmap.put("buss_perm_addr_prf","036");
		hmap.put("buss_pan_card","037");
		hmap.put("buss_ebill","038");
		hmap.put("buss_rent_agrmnt","039");
		hmap.put("buss_shop_act","040");
		hmap.put("buss_gst_certifi","041");
		hmap.put("buss_itr_1","042");
		hmap.put("buss_itr_2","043");
		hmap.put("buss_audit_reprt","044");
		hmap.put("buss_bank_stmnts","045");
		hmap.put("buss_other","046");
		hmap.put("cibil_brwr","047");
		hmap.put("cibil_co_brwr","048");
		hmap.put("repayment_track","049");
		hmap.put("fl_reprt","050");
		hmap.put("insurance_frm","051");
		hmap.put("insurance_calculator_page","052");
		hmap.put("dpn","053");
		hmap.put("id_proof","054");
		hmap.put("app_perm_addr_prf","055");
		hmap.put("app_ebill","056");
		hmap.put("app_photo_id_prf","057");
		hmap.put("app_rent_agree","058");
		hmap.put("app_gas_bill","059");
		hmap.put("app_other","060");
		hmap.put("borro_itr_1","061");
		hmap.put("borro_itr_2","062");
		hmap.put("borro_bank_stmt","063");
		hmap.put("borro_other","064");
		hmap.put("borro_sal_slip","065");
		hmap.put("employee_id_card","066");
		hmap.put("cibil_borro","067");
		hmap.put("repay_track","068");
		hmap.put("fi_report","069");
		hmap.put("ins_form","070");
		hmap.put("ins_cal_page","071");
		hmap.put("co_app_addr_prf","072");
		hmap.put("co_app_perm_addr_prf","073");
		hmap.put("co_app_pan_card","074");
		hmap.put("co_app_aadhar_card","075");
		hmap.put("co_app_ebill","076");
		hmap.put("co_app_photo_id_prf","077");
		hmap.put("co_app_rent_agree","078");
		hmap.put("co_app_gas_bill","079");
		hmap.put("co_app_other","080");
		hmap.put("cibil_co_borro","081");
		hmap.put("co_app_bank stmt","082");
		hmap.put("other_1","083");
		hmap.put("other_2","084");
		hmap.put("other_3","085");
		hmap.put("business_addr_prf","086");
		hmap.put("business_perm_addr_prf","087");
		hmap.put("business_pan_card","088");
		hmap.put("business_ebill","089");
		hmap.put("business_rent_agree","090");
		hmap.put("business_shop_act","091");
		hmap.put("business_gst_certifi","092");
		hmap.put("business_itr_1","093");
		hmap.put("business_itr_2","094");
		hmap.put("business_audit_report","095");
		hmap.put("business_bank_stmt","096");
		hmap.put("business_other","097");
		hmap.put("cibil","098");
		hmap.put("bank_stmnts","099");
		hmap.put("gst_returns","100");
		hmap.put("sales_ledger","110");
		hmap.put("bureau consent","113");

		String docCode = (String) hmap.get(documentName);
		
		return docCode;

	}
	
	public String getCibilStateId(String stateName) {
		HashMap<String,String> hmap = new HashMap<String,String>();
		hmap.put("JAMMU & KASHMIR","01");
		hmap.put("HIMACHAL PRADESH","02");
		hmap.put("PUNJAB","03");
		hmap.put("CHANDIGARH","04");
		hmap.put("UTTARANCHAL","05");
		hmap.put("HARYANA","06");
		hmap.put("DELHI","07");
		hmap.put("RAJASTHAN","08");
		hmap.put("UTTAR PRADESH","09");
		hmap.put("BIHAR","10");
		hmap.put("SIKKIM","11");
		hmap.put("ARUNACHAL PRADESH","12");
		hmap.put("NAGALAND","13");
		hmap.put("MANIPUR","14");
		hmap.put("MIZORAM","15");
		hmap.put("TRIPURA","16");
		hmap.put("MEGHALAYA","17");
		hmap.put("ASSAM","18");
		hmap.put("WEST BENGAL","19");
		hmap.put("JHARKHAND","20");
		hmap.put("ORISSA","21");
		hmap.put("CHHATTISGARH","22");
		hmap.put("MADHYA PRADESH","23");
		hmap.put("GUJARAT","24");
		hmap.put("DAMAN & DIU","25");
		hmap.put("DADRA & NAGAR HAVELI & DAMAN & DIU","26");
		hmap.put("MAHARASHTRA","27");
		hmap.put("ANDHRA PRADESH","28");
		hmap.put("KARNATAKA","29");
		hmap.put("GOA","30");
		hmap.put("LAKSHADWEEP","31");
		hmap.put("KERALA","32");
		hmap.put("TAMIL NADU","33");
		hmap.put("PONDICHERRY","34");
		hmap.put("ANDAMAN & NICOBAR ISLANDS","35");
		hmap.put("TELANGANA","36");
		hmap.put("APO ADDRESS","99");

		
		String stateId = (String) hmap.get(stateName);
		
		return stateId;
	}
	
	public String getCibilAccountType(String accId) {
		HashMap<String,String> hmap = new HashMap<String,String>();
		hmap.put("01","Auto Loan (Personal)");
		hmap.put("02","Housing Loan");
		hmap.put("03","Property Loan");
		hmap.put("04","Loan Against Shares/Securities");
		hmap.put("05","Personal Loan");
		hmap.put("06","Consumer Loan");
		hmap.put("07","Gold Loan");
		hmap.put("08","Education Loan");
		hmap.put("09","Loan to Professional");
		hmap.put("10","Credit Card");
		hmap.put("11","Leasing");
		hmap.put("12","Overdraft");
		hmap.put("13","Two-wheeler Loan");
		hmap.put("14","Non-Funded Credit Facility (Acronym - NFCF)");
		hmap.put("15","Loan Against Bank Deposits (Acronym - LABD)");
		hmap.put("16","Fleet Card");
		hmap.put("17","Commercial Vehicle Loan");
		hmap.put("18","Telco – Wireless");
		hmap.put("19","Telco – Broadband");
		hmap.put("20","Telco – Landline");
		hmap.put("21","Seller Financing");
		hmap.put("22","Seller Financing Soft (Applicable to Enquiry Purpose only)");
		hmap.put("23","GECL Loan Secured");
		hmap.put("24","GECL Loan Unsecured");
		hmap.put("31","Secured Credit Card");
		hmap.put("32","Used Car Loan");
		hmap.put("33","Construction Equipment Loan");
		hmap.put("34","Tractor Loan");
		hmap.put("35","Corporate Credit Card");
		hmap.put("36","Kisan Credit Card");
		hmap.put("37","Loan on Credit Card");
		hmap.put("38","Prime Minister Jaan Dhan Yojana – Overdraft");
		hmap.put("39","Mudra Loans – Shishu / Kishor / Tarun");
		hmap.put("40","Microfinance – Business Loan");
		hmap.put("41","Microfinance – Personal Loan");
		hmap.put("42","Microfinance – Housing Loan");
		hmap.put("43","Microfinance – Other");
		hmap.put("44","Pradhan Mantri Awas Yojana - Credit Link Subsidy Scheme MAY CLSS");
		hmap.put("45","P2P Personal Loan");
		hmap.put("46","P2P Auto Loan");
		hmap.put("47","P2P Education Loan");
		hmap.put("50","Business Loan – Secured");
		hmap.put("51","Business Loan – General");
		hmap.put("52","Business Loan – Priority Sector – Small Business (Acronym - BLPS-SB)");
		hmap.put("53","Business Loan – Priority Sector – Agriculture (Acronym - BLPS-AGR)");
		hmap.put("54","Business Loan – Priority Sector – Others (Acronym - BLPS-OTH)");
		hmap.put("55","Business Non-Funded Credit Facility – General (Acronym - BNFCF-GEN)");
		hmap.put("56","Business Non-Funded Credit Facility – Priority Sector – Small Business (Acronym - BNFCF-PS-SB)");
		hmap.put("57","Business Non-Funded Credit Facility – Priority Sector – Agriculture (Acronym - BNFCF-PS-AGR)");
		hmap.put("58","Business Non-Funded Credit Facility – Priority Sector-Others (Acronym - BNFCF-PS-OTH)");
		hmap.put("59","Business Loan Against Bank Deposits (Acronym - BLABD)");
		hmap.put("61","Business Loan – Unsecured");
		hmap.put("64","Insurance (Acronym - INSURANCE)");
		hmap.put("80","Microfinance Detailed Report (Applicable to Enquiry Purpose only)");
		hmap.put("81","Summary Report (Applicable to Enquiry Purpose only)");
		hmap.put("88","Locate Plus for Insurance (Applicable to Enquiry Purpose only)");
		hmap.put("90","Account Review (Applicable to Enquiry Purpose only)");
		hmap.put("91","Retro Enquiry (Applicable to Enquiry Purpose only)");
		hmap.put("92","Locate Plus (Applicable to Enquiry Purpose only)");
		hmap.put("97","Adviser Liability (Applicable to Enquiry Purpose only)");
		hmap.put("00","Other");
		hmap.put("98","Secured (Account Group for Portfolio Review response)");
		hmap.put("99","Unsecured (Account Group for Portfolio Review response)");
		
		String accType = (String) hmap.get(accId);
		
		return accType;
	}
	
	public String getBankNameByIFSC(String ifsc) {
		HashMap<String,String> hmap = new HashMap<String,String>();
		
		hmap.put("ABHY","ABHYUDAYA COOPERATIVE BANK LIMITED");
		hmap.put("ADBK","THE ADARSH COOPERATIVE URBAN BANK LIMITED");
		hmap.put("ADCC","THE AKOLA-WASHIM DISTRICT CENTRAL COOPERATIVE BANK LTD., AKOLA");
		hmap.put("AHDC","THE AHMEDNAGAR DISTRICT CENTRAL COOPERATIVE BANK LTD");
		hmap.put("AIRP","AIRTEL PAYMENTS BANK LIMITED");
		hmap.put("AJAR","THE AJARA URBAN CO OP BANK LTD AJARA");
		hmap.put("AJHC","AMBARNATH JAIHIND COOP BANK LTD AMBARNATH");
		hmap.put("AKJB","AKOLA JANATA COMMERCIAL COOPERATIVE BANK");
		hmap.put("AMCB","AHMEDABAD MERCANTILE COOPERATIVE BANK");
		hmap.put("AMDN","AHMEDNAGAR MERCHANTS COOP BANK LTD");
		hmap.put("ANZB","AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED");
		hmap.put("APBL","THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED");
		hmap.put("APGB","ANDHRA PRAGATHI GRAMEENA BANK");
		hmap.put("APGV","ANDHRA PRADESH GRAMEENA VIKAS BANK");
		hmap.put("APMC","THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED");
		hmap.put("ARBL","ARVIND SAHAKARI BANK LTD");
		hmap.put("ASBL","APNA SAHAKARI BANK LIMITED");
		hmap.put("AUBL","AU SMALL FINANCE BANK LIMITED");
		hmap.put("AUCB","ALMORA URBAN COOPERATIVE BANK LIMITED");
		hmap.put("BACB","BASSEIN CATHOLIC COOPERATIVE BANK LIMITED");
		hmap.put("BARA","THE BARAMATI SAHAKARI BANK LTD");
		hmap.put("BARB","BANK OF BARODA");
		hmap.put("BARC","BARCLAYS BANK");
		hmap.put("BBKM","BANK OF BAHARAIN AND KUWAIT BSC");
		hmap.put("BCBM","BHARAT COOPERATIVE BANK MUMBAI LIMITED");
		hmap.put("BCEY","BANK OF CEYLON");
		hmap.put("BCHN","BANK OF CHINA LIMITED INDIA BRANCH");
		hmap.put("BDBL","BANDHAN BANK LIMITED");
		hmap.put("BKID","BANK OF INDIA");
		hmap.put("BMCB","BOMBAY MERCANTILE COOPERATIVE BANK LTD");
		hmap.put("BNPA","B N P PARIBAS");
		hmap.put("BNSB","BHAGINI NIVEDITA SAHAKARI BANK LTD PUNE");
		hmap.put("BOFA","BANK OF AMERICA");
		hmap.put("BOTM","MUFG BANK, LTD");
		hmap.put("BUCB","THE BURDWAN CENTRAL CO OPERATIVE BANK LTD");
		hmap.put("CBIN","CENTRAL BANK OF INDIA");
		hmap.put("CCBL","CITIZEN CREDIT COOPERATIVE BANK LIMITED");
		hmap.put("CHAS","JP MORGAN BANK");
		hmap.put("CITI","CITI BANK");
		hmap.put("CIUB","CITY UNION BANK LIMITED");
		hmap.put("CLBL","CAPITAL SMALL FINANCE BANK LIMITED");
		hmap.put("CNRB","CANARA BANK");
		hmap.put("COAS","COASTAL LOCAL AREA BANK LTD");
		hmap.put("COSB","THE COSMOS CO OPERATIVE BANK LIMITED");
		hmap.put("CRES","UBS AG");
		hmap.put("CRGB","CHHATTISGARH RAJYA GRAMIN BANK");
		hmap.put("CRLY","CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK");
		hmap.put("CRUB","SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED");
		hmap.put("CSBK","CSB BANK LIMITED");
		hmap.put("CTCB","CTBC BANK CO LTD");
		hmap.put("DBSS","DBS BANK INDIA LIMITED");
		hmap.put("DCBL","DCB BANK LIMITED");
		hmap.put("DCUB","DARUSSALAM CO OPERATIVE URBAN BANK LTD");
		hmap.put("DEOB","DEOGIRI NAGARI SAHAKARI BANK LTD. AURANGABAD");
		hmap.put("DEUT","DEUTSCHE BANK");
		hmap.put("DICG","DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION");
		hmap.put("DLSC","THE DELHI STATE COOPERATIVE BANK LIMITED");
		hmap.put("DLXB","DHANALAKSHMI BANK");
		hmap.put("DMKJ","DMK JAOLI BANK");
		hmap.put("DNSB","DOMBIVLI NAGARI SAHAKARI BANK LIMITED");
		hmap.put("DOHB","DOHA BANK Q.P.S.C");
		hmap.put("DURG","DURGAPUR STEEL PEOPLES CO-OPERATIVE BANK LTD");
		hmap.put("EBIL","EMIRATES NBD BANK P J S C");
		hmap.put("EIBI","EXPORT IMPORT BANK OF INDIA");
		hmap.put("ESFB","EQUITAS SMALL FINANCE BANK LIMITED");
		hmap.put("ESMF","ESAF SMALL FINANCE BANK LIMITED");
		hmap.put("FDRL","FEDERAL BANK");
		hmap.put("FINO","FINO PAYMENTS BANK");
		hmap.put("GBCB","THE GREATER BOMBAY COOPERATIVE BANK LIMITED");
		hmap.put("GDCB","THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED");
		hmap.put("GSCB","THE GUJARAT STATE COOPERATIVE BANK LIMITED");
		hmap.put("GSSB","GUARDIAN SOUHARDA SAHAKARI BANK NIYAMITA");
		hmap.put("HARC","HARYANA STATE COOPERATIVE BANK");
		hmap.put("HCBL","THE HASTI COOP BANK LTD");
		hmap.put("HDFC","HDFC BANK");
		hmap.put("HPSC","HIMACHAL PRADESH STATE COOPERATIVE BANK LTD");
		hmap.put("HSBC","HSBC BANK");
		hmap.put("HUSB","HUTATMA SAHAKARI BANK LTD");
		hmap.put("HVBK","WOORI BANK");
		hmap.put("IBBK","PT BANK MAYBANK INDONESIA TBK");
		hmap.put("IBKL","IDBI BANK");
		hmap.put("IBKO","INDUSTRIAL BANK OF KOREA");
		hmap.put("ICBK","INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED");
		hmap.put("ICIC","ICICI BANK LIMITED");
		hmap.put("IDFB","IDFC FIRST BANK LTD");
		hmap.put("IDIB","INDIAN BANK");
		hmap.put("INDB","INDUSIND BANK");
		hmap.put("IOBA","INDIAN OVERSEAS BANK");
		hmap.put("IPOS","INDIA POST PAYMENT BANK");
		hmap.put("ITBL","IRINJALAKUDA TOWN CO OPERATIVE BANK LTD");
		hmap.put("JAKA","JAMMU AND KASHMIR BANK LIMITED");
		hmap.put("JANA","JANASEVA SAHAKARI BANK LIMITED");
		hmap.put("JASB","JANASEVA SAHAKARI BANK BORIVLI LIMITED");
		hmap.put("JIOP","JIO PAYMENTS BANK LIMITED");
		hmap.put("JJSB","JALGAON JANATA SAHAKARI BANK LIMITED");
		hmap.put("JPCB","THE JALGAON PEOPELS COOPERATIVE BANK LIMITED");
		hmap.put("JSBL","JANAKALYAN SAHAKARI BANK LIMITED");
		hmap.put("JSBP","JANATA SAHAKARI BANK LIMITED");
		hmap.put("JSFB","JANA SMALL FINANCE BANK LTD");
		hmap.put("JTSC","JANATHA SEVA COOPERATIVE BANK LTD");
		hmap.put("KACE","THE KANGRA CENTRAL COOPERATIVE BANK LIMITED");
		hmap.put("KAIJ","KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED");
		hmap.put("KANG","THE KANGRA COOPERATIVE BANK LIMITED");
		hmap.put("KARB","KARNATAKA BANK LIMITED");
		hmap.put("KBKB","KOOKMIN BANK");
		hmap.put("KCCB","KALUPUR COMMERCIAL COOPERATIVE BANK");
		hmap.put("KJSB","THE KALYAN JANATA SAHAKARI BANK LTD.");
		hmap.put("KKBK","KOTAK MAHINDRA BANK LIMITED");
		hmap.put("KLGB","KERALA GRAMIN BANK");
		hmap.put("KNSB","THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED");
		hmap.put("KOEX","KEB HANA BANK");
		hmap.put("KOLH","THE KOLHAPUR URBAN CO OP BANK LTD");
		hmap.put("KSBK","THE KERALA STATE CO OPERATIVE BANK LTD");
		hmap.put("KSCB","THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED");
		hmap.put("KUCB","THE KARAD URBAN COOPERATIVE BANK LIMITED");
		hmap.put("KVBL","KARUR VYSYA BANK");
		hmap.put("KVGB","KARNATAKA VIKAS GRAMEENA BANK");
		hmap.put("MAHB","BANK OF MAHARASHTRA");
		hmap.put("MAHG","MAHARASHTRA GRAMIN BANK");
		hmap.put("MCAB","THE MEGHALAYA COOPERATIVE APEX BANK LTD");
		hmap.put("MCBL","GS MAHANAGAR CO-OPERATIVE BANK LIMITED,MUMBAI");
		hmap.put("MDBK","MODEL COOPERATIVE BANK LTD");
		hmap.put("MDCB","THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED");
		hmap.put("MHCB","MIZUHO BANK LTD");
		hmap.put("MSBL","MAHESH SAHAKARI BANK LTD PUNE");
		hmap.put("MSCI","MAHARASHTRA STATE COOPERATIVE BANK");
		hmap.put("MSHQ","MASHREQBANK PSC");
		hmap.put("MSLM","THE MUSLIM COOPERATIVE BANK LTD");
		hmap.put("MSNU","THE MEHSANA URBAN COOPERATIVE BANK");
		hmap.put("MUBL","THE MUNICIPAL COOPERATIVE BANK LIMITED");
		hmap.put("MVCB","SIR M VISVESVARAYA CO OPERATIVE BANK LTD");
		hmap.put("NBAD","FIRST ABU DHABI BANK PJSC");
		hmap.put("NBRD","NATIONAL BANK FOR AGRICULTURE AND RURAL DEVELOPMENT");
		hmap.put("NCUB","THE NILAMBUR CO OPERATIVE URBAN BANK LTD NILAMBUR");
		hmap.put("NESF","NORTH EAST SMALL FINANCE BANK LIMITED");
		hmap.put("NGSB","NAGPUR NAGARIK SAHAKARI BANK LIMITED");
		hmap.put("NHBA","NONGHYUP BANK");
		hmap.put("NICB","NEW INDIA COOPERATIVE BANK LIMITED");
		hmap.put("NJBK","NAV JEEVAN CO OP BANK LTD");
		hmap.put("NKGS","NKGSB COOPERATIVE BANK LIMITED");
		hmap.put("NMCB","THE NASIK MERCHANTS COOPERATIVE BANK LIMITED");
		hmap.put("NNSB","NUTAN NAGARIK SAHAKARI BANK LIMITED");
		hmap.put("NOSC","THE BANK OF NOVA SCOTIA");
		hmap.put("NSPB","NSDL PAYMENTS BANK LIMITED");
		hmap.put("NTBL","THE NAINITAL BANK LIMITED");
		hmap.put("NVNM","THE NAVNIRMAN COOPERATIVE BANK LIMITED");
		hmap.put("ORCB","THE ODISHA STATE CO-OPERATIVE BANK LTD");
		hmap.put("PJSB","G P PARSIK BANK");
		hmap.put("PKGB","KARNATAKA GRAMIN BANK");
		hmap.put("PMEC","PRIME COOPERATIVE BANK LIMITED");
		hmap.put("PSBL","PAVANA SAHAKARI BANK LTD");
		hmap.put("PSIB","PUNJAB AND SIND BANK");
		hmap.put("PUCB","THE PANDHARPUR URBAN CO OP. BANK LTD. PANDHARPUR");
		hmap.put("PUNB","PUNJAB NATIONAL BANK");
		hmap.put("PUSD","THE PUSAD URBAN COOPERATIVE BANK LTD PUSAD");
		hmap.put("PYTM","PAYTM PAYMENTS BANK LTD");
		hmap.put("QNBA","QATAR NATIONAL BANK Q.P.S.C");
		hmap.put("RABO","RABOBANK INTERNATIONAL");
		hmap.put("RATN","RBL BANK LIMITED");
		hmap.put("RBIN","RESERVE BANK OF INDIA");
		hmap.put("RBIP","RESERVE BANK OF INDIA");
		hmap.put("RBIS","RESERVE BANK OF INDIA");
		hmap.put("RDCB","RAJNANDGAON DISTRICT CENTRAL COOPERATIVE BANK LTD");
		hmap.put("RMGB","RAJASTHAN MARUDHARA GRAMIN BANK");
		hmap.put("RNSB","RAJKOT NAGRIK SAHAKARI BANK LIMITED");
		hmap.put("RRBP","RAJARAMBAPU SAHAKARI BANK LIMITED");
		hmap.put("RSBL","RAJGURUNAGAR SAHAKARI BANK LIMITED");
		hmap.put("RSCB","THE RAJASTHAN STATE COOPERATIVE BANK LIMITED");
		hmap.put("RSSB","RAJARSHI SHAHU SAHAKARI BANK LTD  PUNE");
		hmap.put("SABR","SBER BANK");
		hmap.put("SAGB","SAPTAGIRI GRAMEENA BANK");
		hmap.put("SANT","SANT SOPANKAKA SAHAKARI BANK LTD");
		hmap.put("SBIN","STATE BANK OF INDIA");
		hmap.put("SBLS","SAMARTH SAHAKARI BANK LTD");
		hmap.put("SCBL","STANDARD CHARTERED BANK");
		hmap.put("SDCB","THE SURAT DISTRICT COOPERATIVE BANK LIMITED");
		hmap.put("SDCE","THE SATARA DISTRICT CENTRAL COOPERATIVE BANK LTD");
		hmap.put("SECB","SREE CHARAN SOUHARDHA CO OPERATIVE BANK LTD");
		hmap.put("SGBA","SAURASHTRA GRAMIN BANK");
		hmap.put("SHBK","SHINHAN BANK");
		hmap.put("SIBL","SOUTH INDIAN BANK");
		hmap.put("SIDC","THE SINDHUDURG DISTRICT CENTRAL CO-OPERATIVE BANK LTD.");
		hmap.put("SJSB","SOLAPUR JANATA SAHAKARI BANK LIMITED");
		hmap.put("SKNB","SHREE KADI NAGARIK SAHAKARI BANK LIMITED");
		hmap.put("SKSB","SHIKSHAK SAHAKARI BANK LIMITED");
		hmap.put("SMBC","SUMITOMO MITSUI BANKING CORPORATION");
		hmap.put("SMCB","SHIVALIK SMALL FINANCE BANK LIMITED");
		hmap.put("SMNB","SMRITI NAGRIK SAHAKARI BANK MARYADIT");
		hmap.put("SNBK","SARASPUR NAGRIK CO OPERATIVE BANK LTD SARASPUR");
		hmap.put("SOGE","SOCIETE GENERALE");
		hmap.put("SPCB","THE SURATH PEOPLES COOPERATIVE BANK LIMITED");
		hmap.put("SRCB","SARASWAT COOPERATIVE BANK LIMITED");
		hmap.put("STCB","SBM BANK INDIA LIMITED");
		hmap.put("SUNB","SURAT NATIONAL COOPERATIVE BANK LIMITED");
		hmap.put("SURY","SURYODAY SMALL FINANCE BANK LIMITED");
		hmap.put("SUSB","SUCO SOUHARDHA SAHAKARI BANK LTD");
		hmap.put("SUTB","SUTEX COOPERATIVE BANK LIMITED");
		hmap.put("SVCB","THE SHAMRAO VITHAL COOPERATIVE BANK");
		hmap.put("SVSH","SHRI VEERSHAIV CO OP BANK LTD");
		hmap.put("TAUB","THE AKOLA URBAN COOPERATIVE BANK LIMITED");
		hmap.put("TBMC","THE BANASKANTHA MERCANTILE COOPERATIVE BANK LTD");
		hmap.put("TBSB","THE THANE BHARAT SAHAKARI BANK LIMITED");
		hmap.put("TCBR","THE COOPERATIVE BANK OF RAJKOT LIMITED");
		hmap.put("TDCB","THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED");
		hmap.put("TGMB","TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED");
		hmap.put("TGRB","TELANGANA GRAMEENA BANK");
		hmap.put("TJSB","TJSB SAHAKARI BANK LTD");
		hmap.put("TMBL","TAMILNAD MERCANTILE BANK LIMITED");
		hmap.put("TMSB","THE MALAD SAHAKARI BANK LTD");
		hmap.put("TNCB","THE NAWANAGAR COOPERATIVE BANK LTD");
		hmap.put("TNSC","THE TAMIL NADU STATE APEX COOPERATIVE BANK");
		hmap.put("TPSC","THE PUNJAB STATE COOPERATIVE BANK LTD");
		hmap.put("TSAB","TELANGANA STATE COOP APEX BANK");
		hmap.put("TSSB","SATARA SAHAKARI BANK LTD");
		hmap.put("TTCB","TTC CO-OPERATIVE BANK LIMITED");
		hmap.put("UBIN","UNION BANK OF INDIA");
		hmap.put("UCBA","UCO BANK");
		hmap.put("UCLB","URBAN CO OPERATIVE BANK LTD BAREILLY");
		hmap.put("UJVN","UJJIVAN SMALL FINANCE BANK LIMITED");
		hmap.put("UNBA","UNITY SMALL FINANCE BANK LIMITED");
		hmap.put("UOVB","UNITED OVERSEAS BANK LIMITED");
		hmap.put("UPCB","UTTAR PRADESH COOPERATIVE BANK");
		hmap.put("URBN","THE URBAN CO OPERATIVE BANK LTD NO ONE SEVEN FIVE EIGHT PERINTHALMANNA");
		hmap.put("USCB","UTTARAKHAND STATE COOPERATIVE BANK LIMITED");
		hmap.put("UTIB","AXIS BANK");
		hmap.put("UTKS","UTKARSH SMALL FINANCE BANK");
		hmap.put("UUCB","THE UDAIPUR URBAN CO OPERATIVE BANK LTD");
		hmap.put("VARA","THE VARACHHA COOPERATIVE BANK LIMITED");
		hmap.put("VASJ","VASAI JANATA SAHAKARI BANK LTD");
		hmap.put("VCOB","THE VIJAY CO OPERATIVE BANK LIMITED");
		hmap.put("VSBA","VIKAS SOUHARDA CO OPERATIVE BANK LIMITED");
		hmap.put("VSBL","THE VISHWESHWAR SAHAKARI BANK LIMITED");
		hmap.put("VTBJ","JSC VTB BANK");
		hmap.put("VVSB","VASAI VIKAS SAHAKARI BANK LIMITED");
		hmap.put("WBSC","THE WEST BENGAL STATE COOPERATIVE BANK");
		hmap.put("YESB","YES BANK");
		hmap.put("ZCBL","THE ZOROASTRIAN COOPERATIVE BANK LIMITED");
		hmap.put("ZSBL","ZILA SAHAKRI BANK LIMITED GHAZIABAD");		
		
		String bankName = (String) hmap.get(ifsc);
		
		return bankName;
		
	}
	
	
	//----------------------------------------------------
	//ADDED BY GAURAV
	
	private List<String> stateNamesList;
	
	public List<String> getStateNamesList() {
		return stateNamesList;
	}
	
	@PostConstruct
	private void loadStateNamesList() {
		String[] arr=new String[] {"ANDHRA PRADESH", "ARUNACHAL PRADESH", "ASSAM", "BIHAR", "CHHATTISGARH", "GOA", "GUJARAT", "HARYANA", "HIMACHAL PRADESH", "JHARKHAND", "KARNATAKA", "KERALA", "MAHARASHTRA", "MADHYA PRADESH", "MANIPUR", "MEGHALAYA", "MIZORAM", "NAGALAND", "ODISHA", "PUNJAB", "RAJASTHAN", "SIKKIM", "TAMIL NADU", "TRIPURA", "TELANGANA", "UTTAR PRADESH", "UTTARAKHAND", "WEST BENGAL", "ANDAMAN AND NICOBAR", "CHANDIGARH", "DADRA AND NAGAR HAVELI AND DAMAN AND DIU", "DELHI", "JAMMU AND KASHMIR", "LADAKH", "LAKSHADWEEP", "PUDUCHERRY"};
		stateNamesList=Arrays.asList(arr);
	}
}
